// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CreateAppointment', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CreateAppointment', async function() {
    await driver.get("http://localhost:5173/appointments")
    await driver.manage().window().setRect({ width: 1920, height: 1055 })
    await driver.findElement(By.css(".container > div > .ui:nth-child(2)")).click()
    await driver.findElement(By.name("date")).click()
    await driver.findElement(By.name("date")).sendKeys("2024-09-24T14:47")
    await driver.findElement(By.css(".field:nth-child(2) > .field")).click()
    await driver.findElement(By.name("reason")).click()
    await driver.findElement(By.name("reason")).sendKeys("This is a test.")
    await driver.findElement(By.css(".search:nth-child(1)")).click()
    await driver.findElement(By.css(".item:nth-child(5)")).click()
    await driver.findElement(By.css(".ui:nth-child(4)")).click()
  })
})
