# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateAppointment():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createAppointment(self):
    self.driver.get("http://localhost:5173/appointments")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.CSS_SELECTOR, ".container > div > .ui:nth-child(2)").click()
    self.driver.find_element(By.NAME, "date").click()
    self.driver.find_element(By.NAME, "date").send_keys("2024-09-24T14:47")
    self.driver.find_element(By.CSS_SELECTOR, ".field:nth-child(2) > .field").click()
    self.driver.find_element(By.NAME, "reason").click()
    self.driver.find_element(By.NAME, "reason").send_keys("This is a test.")
    self.driver.find_element(By.CSS_SELECTOR, ".search:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ui:nth-child(4)").click()
  
