# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup(self):
    self.driver.get("http://localhost:5173/")
    self.driver.set_window_size(1920, 1055)
    self.driver.find_element(By.NAME, "first_name").click()
    self.driver.find_element(By.NAME, "first_name").send_keys("Test")
    self.driver.find_element(By.NAME, "last_name").send_keys("Test")
    self.driver.find_element(By.NAME, "date_of_birth").send_keys("0002-01-01")
    self.driver.find_element(By.NAME, "date_of_birth").send_keys("0020-01-01")
    self.driver.find_element(By.NAME, "date_of_birth").send_keys("0202-01-01")
    self.driver.find_element(By.NAME, "date_of_birth").send_keys("2024-01-01")
    self.driver.find_element(By.NAME, "gender").click()
    dropdown = self.driver.find_element(By.NAME, "gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Cisgender']").click()
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("123 Test St, Test, CO 80401")
    self.driver.find_element(By.NAME, "phone_number").click()
    self.driver.find_element(By.NAME, "phone_number").send_keys("123-456-7890")
    self.driver.find_element(By.NAME, "insurance_id").click()
    self.driver.find_element(By.NAME, "insurance_id").send_keys("test123")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("test@test.com")
    self.driver.find_element(By.NAME, "password_hash").click()
    self.driver.find_element(By.NAME, "password_hash").send_keys("password")
    self.driver.find_element(By.NAME, "confirmPassword").click()
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("password")
    self.driver.find_element(By.CSS_SELECTOR, ".blue").click()
  
